name: Build & attach ZIP for HACS

on:
  release:
    types: [published, prereleased]

permissions:
  contents: write

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Byg/forbered dist — tilpas hvis du har npm build
      - name: Prepare dist (bundle + media)
        run: |
          mkdir -p dist/media/thermostat-guide
          cp thermostat-pro-timeline.js dist/
          [ -d media/thermostat-guide ] && rsync -a media/thermostat-guide/ dist/media/thermostat-guide/

      - name: Verify dist
        run: |
          test -f dist/thermostat-pro-timeline.js

      # VIGTIGT: zip INDHOLDET af dist/, ikke mappen, så filer havner i roden ved udpakning
      - name: Create ZIP for HACS (contents of dist/)
        run: |
          cd dist
          zip -r ../thermostat-pro-timeline.zip . \
            -x "**/__pycache__/*" "**/*.map" ".DS_Store" ".git/*"
          cd ..

      - name: Upload ZIP asset to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: thermostat-pro-timeline.zip
          fail_on_unmatched_files: true
