name: Build & attach JS (with assets)

on:
  release:
    types: [published, prereleased]

permissions:
  contents: write

jobs:
  upload-asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare dist (bundle + media)
        run: |
          mkdir -p dist/media/thermostat-guide
          cp thermostat-pro-timeline.js dist/
          [ -d media/thermostat-guide ] && rsync -a media/thermostat-guide/ dist/media/thermostat-guide/

      - name: Verify dist
        run: |
          test -f dist/thermostat-pro-timeline.js
          test -d dist/media/thermostat-guide

      - name: Precompress JS (optional)
        run: gzip -kf dist/thermostat-pro-timeline.js

      - name: Commit dist to repo (so HACS installs all files)
        uses: EndBug/add-and-commit@v9
        with:
          add: dist
          message: "build: dist for ${{ github.event.release.tag_name }}"
          default_author: github_actions
