name: Attach JS to Release (HACS)

on:
  release:
    types: [published, prereleased]

permissions:
  contents: write

jobs:
  upload-asset:
    runs-on: ubuntu-latest
    env:
      BUNDLE: thermostat-pro-timeline.js
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Hvis du bygger via npm: indsæt build-steps her (npm ci && npm run build)

      - name: Locate bundle
        id: locate
        run: |
          if [ -f "dist/${BUNDLE}" ]; then
            echo "path=dist/${BUNDLE}" >> "$GITHUB_OUTPUT"
            echo "Found: dist/${BUNDLE}"
          elif [ -f "${BUNDLE}" ]; then
            echo "path=${BUNDLE}" >> "$GITHUB_OUTPUT"
            echo "Found: ${BUNDLE}"
          else
            echo "::error ::Bundle not found: ${BUNDLE} (checked repo root and dist/)"
            exit 1
          fi

      - name: Upload JS asset to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.locate.outputs.path }}
          fail_on_unmatched_files: true
