name: Build & Attach ZIP for HACS (Release mode)

on:
  release:
    types: [published, prereleased]

permissions:
  contents: write

jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    env:
      BUNDLE: thermostat-pro-timeline.js
      ZIP_NAME: thermostat-pro-timeline.zip
    steps:
      - uses: actions/checkout@v4

      # Hvis du bygger via npm, så indsæt build her (npm ci && npm run build)

      - name: Prepare dist (bundle + media)
        run: |
          set -e
          mkdir -p dist
          # sikr bundlen findes i dist/
          if [ -f "dist/${BUNDLE}" ]; then
            echo "Bundle OK: dist/${BUNDLE}"
          elif [ -f "${BUNDLE}" ]; then
            cp "${BUNDLE}" "dist/${BUNDLE}"
          else
            echo "::error ::Bundle not found: ${BUNDLE}"
            exit 1
          fi
          # kopier evt. mediemapper fra roden ind i dist/
          [ -d media ] && rsync -a media/ dist/media/
          [ -d thermostat-guide ] && rsync -a thermostat-guide/ dist/thermostat-guide/

      - name: Verify dist contents
        run: |
          test -f "dist/${BUNDLE}"
          echo "Dist tree:"
          find dist -maxdepth 3 -type f | sed 's/^/ - /'

      # Zip INDHOLDET af dist/ (ikke selve mappen)
      - name: Create ZIP from dist/ contents
        run: |
          rm -f "${ZIP_NAME}"
          cd dist
          zip -r "../${ZIP_NAME}" . \
            -x "**/__pycache__/*" "**/*.map" ".DS_Store" ".git/*"
          cd ..

      - name: Upload single ZIP asset to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.ZIP_NAME }}
          fail_on_unmatched_files: true
